import getpass


DEFAULT_PREFIX = 'dcgov-thelab'
DEFAULT_BOX_PREFIX = DEFAULT_PREFIX + '-ec2'
DEFAULT_SECURITY_GROUP_PREFIX = DEFAULT_PREFIX + '-sg'

DEFAULT_CONSUL_BOX_NAME = DEFAULT_BOX_PREFIX + '-consul'
DEFAULT_SPARK_CLUSTER_PREFIX = DEFAULT_BOX_PREFIX + '-spark-' + getpass.getuser()

DEFAULT_CONSUL_SECURITY_GROUP = DEFAULT_SECURITY_GROUP_PREFIX + '-consul-default'
DEFAULT_SPARK_SECURITY_GROUP = DEFAULT_SECURITY_GROUP_PREFIX + '-spark-default'
